"use client";

import { useMemo, useState } from "react";
import VersionDock from "../version-dock";
import { BASE_PATH } from "../base-path";

type Lang="ru"|"ky"|"uz"|"zh";
const ui={
  ru:{label:"Русский",nav:["Закупки","Поставщики","Логистика","Защита"],eyebrow:"Платформа прозрачных поставок",title:"Ваша поставка — под контролем от фабрики до магазина.",lead:"Проверенные китайские производители, единый запрос цен, контроль качества и железнодорожная доставка в Центральную Азию.",search:"Товар, фото, SKU или фабрика",action:"Начать закупку",rfq:"Запрос цен",workspace:"Закупки с понятной экономикой",sub:"Сравните цену, партию, поставщика и срок прибытия до отправки запроса.",quote:"Добавить",freight:"Стоимость доставки",days:"дней",verified:"Поставщик проверен"},
  ky:{label:"Кыргызча",nav:["Сатып алуу","Жеткирүүчүлөр","Логистика","Коргоо"],eyebrow:"Ачык жеткирүү платформасы",title:"Жүк фабрикадан дүкөнгө чейин көзөмөлдө.",lead:"Текшерилген кытай өндүрүүчүлөрү, бирдиктүү баа суроо, сапат көзөмөлү жана Борбор Азияга темир жол жеткирүүсү.",search:"Товар, сүрөт, SKU же фабрика",action:"Сатып алууну баштоо",rfq:"Баа суроо",workspace:"Экономикасы түшүнүктүү сатып алуулар",sub:"Суроо жөнөтүүдөн мурун бааны, партияны, жеткирүүчүнү жана жетүү мөөнөтүн салыштырыңыз.",quote:"Кошуу",freight:"Жеткирүү баасы",days:"күн",verified:"Жеткирүүчү текшерилген"},
  uz:{label:"O‘zbekcha",nav:["Xarid","Yetkazuvchilar","Logistika","Himoya"],eyebrow:"Shaffof yetkazib berish platformasi",title:"Yukingiz fabrikadan do‘kongacha nazoratda.",lead:"Tekshirilgan Xitoy ishlab chiqaruvchilari, yagona narx so‘rovi, sifat nazorati va Markaziy Osiyoga temir yo‘l yetkazib berish.",search:"Mahsulot, rasm, SKU yoki fabrika",action:"Xaridni boshlash",rfq:"Narx so‘rovi",workspace:"Iqtisodi aniq xaridlar",sub:"So‘rov yuborishdan oldin narx, partiya, yetkazuvchi va yetib kelish muddatini solishtiring.",quote:"Qo‘shish",freight:"Yetkazish narxi",days:"kun",verified:"Yetkazuvchi tekshirilgan"},
  zh:{label:"中文",nav:["采购工作台","认证供应商","物流追踪","交易保障"],eyebrow:"透明的跨境供应链平台",title:"从中国工厂到你的店，每一步都看得见。",lead:"认证中国制造商、统一询价、质量检验与中吉乌铁路运输，为中亚商贩建立一条可控的进货链路。",search:"输入商品、图片、SKU 或工厂名称",action:"开始采购",rfq:"询价单",workspace:"采购成本，发出询价前就算清楚",sub:"把货价、起订量、供应商资质与预计到货时间放在一起比较。",quote:"加入询价",freight:"运输成本",days:"天",verified:"供应商已核验"}
} as const;

const items=[
  {names:{ru:"Электрочайник 2 л",ky:"2л электр чайнек",uz:"2l elektr choynak",zh:"2L 不锈钢电热水壶"},sku:"CN-HM-0248",price:"¥23.80",moq:"24",eta:"14",score:"4.9",pos:"p1",image:`${BASE_PATH}/product-kettle.webp`},
  {names:{ru:"Зимняя куртка унисекс",ky:"Кышкы унисекс күрмө",uz:"Uniseks qishki kurtka",zh:"基础加厚长棉服"},sku:"CN-FW-0330",price:"¥72.50",moq:"30",eta:"18",score:"4.8",pos:"p2",image:`${BASE_PATH}/product-coat.webp`},
  {names:{ru:"Дрель 21 В с набором",ky:"21V дрель топтому",uz:"21V drel to‘plami",zh:"21V 电钻工具套装"},sku:"CN-TL-0081",price:"¥68.00",moq:"10",eta:"16",score:"4.9",pos:"p3",image:`${BASE_PATH}/product-drill.webp`},
  {names:{ru:"Набор органайзеров",ky:"Сактоо кутулары",uz:"Saqlash qutilari",zh:"透明家居收纳套装"},sku:"CN-ST-1106",price:"¥11.60",moq:"20",eta:"12",score:"4.7",pos:"p4",image:`${BASE_PATH}/product-storage.webp`},
];

function RailLinkLogo({inverse=false}:{inverse?:boolean}){
  return <div className={`v3r-logo ${inverse?"inverse":""}`}><svg viewBox="0 0 58 48" aria-hidden="true"><path d="M47 9H21C12 9 6 15 6 24s6 15 15 15h26"/><path className="arrow" d="m29 16 13 8-13 8"/><circle cx="47" cy="9" r="4"/><circle cx="47" cy="39" r="4"/><circle cx="6" cy="24" r="4"/></svg><span><b>中亚商机网</b><small>SUPPLY CHAIN FOR CENTRAL ASIA</small></span></div>;
}

function V3Brand({close}:{close:()=>void}){
  return <div className="v3r-brand">
    <section className="v3r-brand-hero"><button onClick={close}>← 返回平台界面</button><span>CONCEPT 03 · SUPPLY CHAIN</span><h1>信任不是一句口号，<br/>是一条完整记录。</h1><p>方案三把中亚商机网定位为“跨境采购基础设施”：克制、专业、可验证，适合长期承载大额采购与供应链服务。</p><b>VI / 03</b></section>
    <section className="v3r-brand-logo"><header><span>01</span><div><h2>可追踪商路标</h2><p>C 形线路代表 China 与 Central Asia；三个铜色节点分别对应工厂、跨境枢纽与目的市场，中间箭头代表持续履约。</p></div></header><div className="v3r-logo-board navy"><RailLinkLogo inverse/><small>深色主应用</small></div><div className="v3r-logo-board paper"><RailLinkLogo/><small>浅色商务应用</small></div><aside><b>最小宽度</b><span>组合标 132px / 图形标 22px</span><b>保护空间</b><span>以端点圆形直径的 2 倍为最小留白</span><b>禁用方式</b><span>不拉伸、不渐变、不叠加国旗与火车图案</span></aside><a href={`${BASE_PATH}/logo-v3r.svg`} download>下载方案三 Logo SVG ↓</a></section>
    <section className="v3r-brand-color"><header><span>02</span><div><h2>专业色彩</h2><p>以铁路蓝与票据白构成可信底色，铜色只用于确认节点与重要数字。</p></div></header><div><article style={{background:"#0D2942"}}><b>铁路深蓝</b><code>#0D2942</code><span>45%</span></article><article style={{background:"#2E5E91"}}><b>商务蓝</b><code>#2E5E91</code><span>20%</span></article><article style={{background:"#B77949"}}><b>节点铜</b><code>#B77949</code><span>8%</span></article><article style={{background:"#2F7465"}}><b>履约绿</b><code>#2F7465</code><span>7%</span></article><article className="paper"><b>票据白</b><code>#F4F3EF</code><span>20%</span></article></div></section>
    <section className="v3r-brand-type"><header><span>03</span><div><h2>信息层级</h2><p>标题建立判断，等宽数字建立证据。</p></div></header><div><small>HEADLINE / Noto Serif SC</small><b>货到哪里，<br/>记录就到哪里。</b></div><pre>SUPPLIER       VERIFIED<br/>UNIT PRICE     ¥ 23.80<br/>MOQ            24 PCS<br/>RAIL ETA       14 DAYS<br/>ORDER STATUS   ON TRACK</pre></section>
    <section className="v3r-brand-photo"><img src={`${BASE_PATH}/v3-rail-hero.webp`} alt="铁路货运场站与物流工作人员" width="1280" height="853" loading="lazy" decoding="async"/><div><span>04 / PHOTOGRAPHY</span><h2>记录真实运行，不制造未来幻觉。</h2><p>只使用真实的铁路、仓库、验货、装箱和商贩经营场景。画面冷静、有秩序；禁止赛博霓虹、全息数据、夸张速度线和虚构国家标识。</p></div></section>
    <section className="v3r-brand-components"><header><span>05</span><div><h2>组件与语气</h2><p>重要动作沉稳明确，绿色只表示已验证或已完成。</p></div></header><div><button>创建询价单</button><span>✓ 供应商已核验</span><b>¥23.80</b><i>预计 14 天</i></div><blockquote>不说：“全链路数字化赋能。”<br/>要说：“工厂已核验；24 件起订；铁路预计 14 天；费用分项可查。”</blockquote></section>
  </div>;
}

export default function ConceptThree(){
  const [lang,setLang]=useState<Lang>("ru");
  const [market,setMarket]=useState<"kg"|"uz">("kg");
  const [guide,setGuide]=useState(false);
  const [count,setCount]=useState(3);
  const [query,setQuery]=useState("");
  const [category,setCategory]=useState("all");
  const [notice,setNotice]=useState("");
  const t=ui[lang];
  const shown=useMemo(()=>items.filter(x=>!query||x.names[lang].toLowerCase().includes(query.toLowerCase())),[query,lang]);
  const add=(x:string)=>{setCount(v=>v+1);setNotice(`${x} · ${lang==="zh"?"已加入询价单":"добавлено в запрос"}`)};
  if(guide)return <main className="v3r-shell"><V3Brand close={()=>setGuide(false)}/><VersionDock active={3}/></main>;
  return <main className="v3r-shell">
    <div className="v3r-status"><span><i/>铁路线路正常运行</span><span>当前平均妥投 96.4%</span><span>供应商核验中心：义乌 / 广州 / 深圳</span><b>服务时间 09:00–21:00 UTC+8</b></div>
    <header className="v3r-header"><RailLinkLogo/><nav>{t.nav.map((x,i)=><a href={i===0?"#v3r-work":i===2?"#v3r-route":"#v3r-assurance"} key={x}>{x}</a>)}</nav><div><button onClick={()=>setGuide(true)}>品牌 VI · 03</button><select value={lang} onChange={e=>setLang(e.target.value as Lang)} aria-label="Language">{(Object.keys(ui) as Lang[]).map(k=><option value={k} key={k}>{ui[k].label}</option>)}</select><button className="v3r-rfq" onClick={()=>setNotice(lang==="zh"?"询价单可进入供应商比价":"Запрос готов к сравнению")}>{t.rfq}<b>{count}</b></button></div></header>
    {notice&&<button className="v3r-toast" onClick={()=>setNotice("")}>{notice}<b>×</b></button>}
    <section className="v3r-hero"><div className="v3r-hero-copy"><span>{t.eyebrow}</span><h1>{t.title}</h1><p>{t.lead}</p><div><a href="#v3r-work">{t.action} →</a><button onClick={()=>document.querySelector("#v3r-route")?.scrollIntoView({behavior:"smooth"})}>查看铁路线路</button></div><footer><span><b>2,408</b>认证中国供应商</span><span><b>12–18</b>平均运输天数</span><span><b>4</b>种语言服务</span></footer></div><div className="v3r-hero-photo"><img src={`${BASE_PATH}/v3-rail-hero.webp`} alt="中吉乌铁路货运场站" width="1280" height="853" fetchPriority="high" decoding="async"/><div><span><i/>CKU RAIL / 正常</span><b>{market==="kg"?"义乌 → 比什凯克":"义乌 → 塔什干"}</b><small>下一节点：乌鲁木齐集结中心</small><em>预计 {market==="kg"?"14":"17"} {t.days}</em></div></div></section>
    <section className="v3r-search"><div><span>搜索货源</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/><button>{t.action}</button></div><aside><small>目的市场</small><button className={market==="kg"?"active":""} onClick={()=>setMarket("kg")}>🇰🇬 Бишкек</button><button className={market==="uz"?"active":""} onClick={()=>setMarket("uz")}>🇺🇿 Ташкент</button></aside></section>
    <section className="v3r-work" id="v3r-work"><header><div><span>PROCUREMENT WORKSPACE</span><h2>{t.workspace}</h2><p>{t.sub}</p></div><button onClick={()=>setNotice(lang==="zh"?"上传找货将在完整产品阶段启用":"Поиск по фото будет доступен в полном продукте")}>上传图片找同款</button></header><div className="v3r-work-grid"><aside><span>商品分类</span>{[["all","全部货源","2,408"],["home","家居日用","386"],["fashion","服装鞋靴","742"],["tools","五金工具","264"],["digital","数码电器","418"],["auto","汽车用品","189"]].map(([id,n,c])=><button className={category===id?"active":""} onClick={()=>setCategory(id)} key={id}><span>{n}</span><b>{c}</b></button>)}<div><span>采购保障</span><b>订单资金由平台节点托管</b><small>查看保障规则 →</small></div></aside><div className="v3r-products">{shown.map(x=><article key={x.sku}><div className={`v3r-product-photo ${x.pos}`}><img src={x.image} alt={x.names[lang]} width="720" height="720" loading="lazy" decoding="async"/><span>{x.sku}</span><i>♡</i></div><div className="v3r-product-main"><span><i/> {t.verified}</span><h3>{x.names[lang]}</h3><small>义乌市瑞联日用品厂 · 复购率 38%</small><div><b>{x.price}</b><em>中国工厂价</em></div><dl><div><dt>起订量</dt><dd>{x.moq} 件</dd></div><div><dt>预计到货</dt><dd>{x.eta} {t.days}</dd></div><div><dt>供应商评分</dt><dd>★ {x.score}</dd></div></dl><button onClick={()=>add(x.names[lang])}>{t.quote} +</button></div></article>)}{shown.length===0&&<p className="v3r-empty">暂无匹配商品 / Ничего не найдено</p>}</div><aside className="v3r-summary"><span>当前询价单</span><b>{count} 件商品</b><dl><div><dt>商品估值</dt><dd>¥ 3,842</dd></div><div><dt>质检与集货</dt><dd>¥ 286</dd></div><div><dt>{t.freight}</dt><dd>{market==="kg"?"¥ 1,486":"¥ 1,728"}</dd></div></dl><div><small>预计采购总额</small><b>{market==="kg"?"¥ 5,614":"¥ 5,856"}</b><span>不含目的国税费</span></div><button onClick={()=>setNotice(lang==="zh"?"已生成供应商比价申请":"Запрос на сравнение создан")}>提交供应商比价 →</button><p>提交后由平台确认阶梯价、库存与交期，不会直接付款。</p></aside></div></section>
    <section className="v3r-route" id="v3r-route"><header><div><span>LOGISTICS CONTROL</span><h2>中吉乌铁路运输节点</h2></div><div><i/>线路运行正常<b>{market==="kg"?"14":"17"} 天预计到达</b></div></header><div className="v3r-route-body"><div className="v3r-timeline"><article className="done"><b>01</b><span>义乌集货仓<small>收货、清点、合单</small></span><time>DAY 01–02</time></article><article className="done"><b>02</b><span>乌鲁木齐编组<small>铁路装载与单据确认</small></span><time>DAY 03–05</time></article><article className="current"><b>03</b><span>喀什 / 边境换装<small>当前运输节点</small></span><time>DAY 06–08</time></article><article><b>04</b><span>{market==="kg"?"比什凯克交付中心":"塔什干交付中心"}<small>到站通知与末端交付</small></span><time>{market==="kg"?"DAY 12–18":"DAY 14–20"}</time></article></div><aside><span>参考运输参数</span><dl><div><dt>计费重量</dt><dd>120 KG</dd></div><div><dt>体积</dt><dd>0.86 M³</dd></div><div><dt>参考单价</dt><dd>{market==="kg"?"¥ 12.38":"¥ 14.40"}/KG</dd></div><div><dt>预计费用</dt><dd>{market==="kg"?"¥ 1,486":"¥ 1,728"}</dd></div></dl><button onClick={()=>setNotice(lang==="zh"?"物流顾问会根据品类复核运输条件":"Логист проверит условия перевозки")}>咨询物流顾问</button></aside></div></section>
    <section className="v3r-assurance" id="v3r-assurance"><header><span>TRADE ASSURANCE</span><h2>把风险控制在付款之前。</h2></header><div><article><b>01</b><h3>工厂身份核验</h3><p>营业执照、生产地址、主营类目、产能与历史履约信息可追溯。</p></article><article><b>02</b><h3>样品与验货</h3><p>支持样品确认、抽检、数量核对、包装检查与验货报告。</p></article><article><b>03</b><h3>费用分项透明</h3><p>货款、国内运输、集货、质检和跨境运输分别列示。</p></article><article><b>04</b><h3>异常协助处理</h3><p>缺货、货不对板或运输异常均保留节点证据并进入处理流程。</p></article></div></section>
    <footer className="v3r-footer"><RailLinkLogo inverse/><p>可靠，不来自承诺。来自每一个可核验的节点。</p><span>© 2026 中亚商机网</span></footer>
    <VersionDock active={3}/>
  </main>;
}
